# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ybf 0.1.0"
license = "MIT"
licenselink = ""
description = ""
homepage = "http://yellowblackfish.io"
tags = ["", ""]
features = ["", ""]
min_version = 0.17

[author]
  name = "William Pansky"
  homepage = "http://williampansky.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
